# Generated by Django 4.1 on 2022-08-30 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0002_alter_routes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cook',
            options={'ordering': ['-publish', 'title'], 'verbose_name': 'Маршруты', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterField(
            model_name='cook',
            name='desc',
            field=models.TextField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='image',
            field=models.ImageField(upload_to='static', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
