# Generated by Django 4.1.1 on 2022-09-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0011_alter_comment_options_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',), 'verbose_name_plural': 'Комментарии'},
        ),
    ]
